Repository Harsh-jot/HacktoberFest-2023, pull requests merged in 2023-10, with the labels that each got.

#5 Create ReverseString.c
  Programs/Reverse String/ReverseString.c
Labels: hacktoberfest2023, hacktoberfest, hacktoberfest-accepted, hacktoberfest-approved, approved

#6 Create PrimeNumber.java
  Programs/Prime Number Checker/PrimeNumber.java
Labels: hacktoberfest2023, hacktoberfest, hacktoberfest-accepted, hacktoberfest-approved, approved

#8 Create ReverseString.cpp
  Programs/Reverse String/ReverseString.cpp
Labels: hacktoberfest2023, hacktoberfest, hacktoberfest-accepted, hacktoberfest-approved, approved

#9 Create BinarySearch.cpp
  Programs/Binary Search/BinarySearch.cpp
Labels: hacktoberfest2023, hacktoberfest, hacktoberfest-accepted, hacktoberfest-approved, approved

#10 Create Palindrome.cpp
  Programs/Palindrome/Palindrome.cpp
Labels: hacktoberfest2023, hacktoberfest, hacktoberfest-accepted, hacktoberfest-approved, approved

#12 Create PrimeNumber.c
  Programs/Prime Number Checker/PrimeNumber.c
Labels: hacktoberfest2023, hacktoberfest, hacktoberfest-accepted, hacktoberfest-approved, approved

#14 Create Fibonacci.c
  Programs/Fibonacci Series/Fibonacci.c
Labels: hacktoberfest2023, hacktoberfest, hacktoberfest-accepted, hacktoberfest-approved, approved

#20 Added few Sorting Programs
  Programs/Sorting/HeapSort.java
  Programs/Sorting/QuickSort.java
Labels: hacktoberfest2023, hacktoberfest, hacktoberfest-accepted, hacktoberfest-approved, approved

#18 Create GuessTheNumber.java
  Programs/Guess The Number/GuessTheNumber.java
Labels: hacktoberfest2023, hacktoberfest, hacktoberfest-accepted, hacktoberfest-approved

#23 Create StonePaperScissor.java
  Programs/Stone Paper Scissor/StonePaperScissor.java
Labels: hacktoberfest2023, hacktoberfest-accepted, hacktoberfest-approved

#22 Second Largest Element.cpp
  Programs/Second Largest Element in Array/Second Largest Element.cpp
Labels: good first issue, hacktoberfest2023, hacktoberfest-accepted, hacktoberfest-approved

#34 Feat : add loopnumber with java
  Programs/LoopMumber/loopNumber.java
Labels: hacktoberfest2023
